version: 2.1
jobs:
  chromedriver_job:
    docker:
      #- image: govindbhardwaj/node-10.15.3:webdrivers-v1
      - image: govindbhardwaj/node:10.15.3-webdrivers-v2
    resource_class: small
    steps:
      - run:
          name: Install chromedriver
          command: |
            whoami
            ls -l /root/project
            ls -l /root
            npm install chromedriver
          when: always
workflows:
  chromedriver_workflow:
    jobs:
      - chromedriver_job:
          filters:
            branches:
              only:
                - master